### ISSUE TITLE
add a configurable flag to redispatch and really connect read pairs

### ISSUE THREAD

**Issue by rbuels** [GMOD/bam-js#10]

**Comment by rbuels** [comment]
like, really connect them.

connected.

**Comment by cmdcolin** [comment]
I made a little progress on this by attacking both jbrowse code and this module code for redispatching, and making a read cloud type track

Here's a screenshot
![screenshot-localhost-2018 10 12-11-43-01 1](https://user-images.githubusercontent.com/6511937/46879433-17dfa280-ce14-11e8-9f30-52b227573b8e.png)

Some TODOs

1. Make a 'paired read glyph' so that you get actual alignment type views
2. Make a efficient data model for paired reads (currently just initialize a simplefeature with some bare bones data)
3. Enable the view as pairs flag so that it can be turned on and off

There are many more tiny tasks but it is a start

**Comment by rbuels** [comment]
Awesome! Really shaping up.

**Comment by cmdcolin** [comment]
Made a little more progress, less hacky especially on the jbrowse side

![screenshot-localhost-2018 10 15-14-05-37](https://user-images.githubusercontent.com/6511937/46969359-ce958a00-d083-11e8-8598-bd80b864f801.png)
![screenshot-localhost-2018 10 15-14-07-33](https://user-images.githubusercontent.com/6511937/46969365-d48b6b00-d083-11e8-9ffb-4b3eb4a78846.png)

The detail popup is modified to contain both reads side by side

**Comment by rbuels** [comment]
Whoa

**Comment by cmdcolin** [comment]
Got mismatch rendering going with a little bit of non-DRY code duplication

Some TODOs

- If paired reads are overlapping (which can be quite common) it is a little hard to display both reads at once and especially the mismatches of both reads. I don't know if there is a nice solution to this, things like alpha transparency could make it look weird
- Redispatching isn't really tested yet and there are some visible places where it is probably not working in the visualization. I hadn't yet added a unit tests for this in bam-js module yet so hopefully this will improve :)

![screenshot-localhost-2018 10 15-19-04-28](https://user-images.githubusercontent.com/6511937/46983127-2dbbc480-d0ad-11e8-9cac-2caa1cbde4f0.png)

**Comment by rbuels** [comment]
With overlapping, maybe you could “bump” the second one down to make a
double height glyph? Might provide a good indication visually that some
things are awry

**Comment by rbuels** [comment]
can this be closed? looks like the code for this is released

**Comment by rbuels** [comment]
well, closing for now

**Comment by cmdcolin** [comment]
True, this was done for bam-js
