### ISSUE TITLE
fetch size limit error with `pairAcrossChr` 

### ISSUE THREAD

**Issue by sehilyi** [GMOD/bam-js#84]
Thank you for this awesome library!

I was using this in HiGlass/Gosling.js with the `opt.pairAcrossChr` option turned on

```js
bamFile.getRecordsForRange(..., {
  viewAsPairs: true,
  pairAcrossChr: true
})
```

but was getting the following error and warning messages:

<img width="1509" alt="Screen Shot 2021-11-05 at 6 19 46 AM" src="https://user-images.githubusercontent.com/9922882/140524876-2c6f9ac9-7244-45ef-b115-4f5933965fb2.png">

> Error: data size of 1,073,213,398 bytes exceeded fetch size limit of 500,000,000 bytes

Could you suggest how to work around this issue? 

Perhaps, searching `pairAcrossChr` is an expensive operation and is not supported for large data? (e.g., I was using a 200GB BAM file w/ a BAI file).

**Comment by cmdcolin** [comment]
hmm...hard to say. there may be something weird going on or it could be the particular dataset. if you have the file I could check it out

the way viewAsPairs works is 

- you request a particular region chr:start-end from a BAM file, and then if the features in that region are paired with another region in the file (RNEXT:PNEXT) then it literally goes and tries to fetch those regions also e.g. RNEXT:PNEXT-PNEXT+1
that can in some cases lead to a lot of data being fetched especially if you hit a repeat that happens to be paired aberrantly to many places on the genome

note that the viewAsPairs option was developed for jbrowse 1 because we wanted to synthesize a "paired feature" up front when we encounter a pair. there are probably other methods that don't require the viewAsPairs code

**Comment by cmdcolin** [comment]
also to be clear, you can override the fetchSizeLimit in the constructor if you want to ignore this! maybe can close for now
